from typing import Any, Dict, Optional

from core.logger import get_logger
from services.memory_service import (
    DEFAULT_CONTEXT_LIMIT,
    DEFAULT_SESSION_ID,
    MemoryService,
    format_conversation_history,
)
from services.ollama_service import OllamaService
from services.prompt_loader import PromptLoader

logger = get_logger(__name__)


class CareerAgent:
    """
    CareerAgent handles career-related requests such as CV optimization,
    cover letters, interview preparation, LinkedIn optimization, and
    professional career development.
    """

    AGENT_ID: str = "career_agent"

    def __init__(self, memory_service: Optional[MemoryService] = None):
        self.llm = OllamaService()
        self.prompt_loader = PromptLoader()
        self.memory = memory_service or MemoryService()

        # Load the system prompt during initialization
        self.system_prompt = self.prompt_loader.load("career_agent.txt")

        logger.info("CareerAgent initialized successfully.")

    def handle(self, action: str, payload: Dict[str, Any]) -> str:
        """
        Executes a career-related request.

        Args:
            action: The requested action (e.g. "execute").
            payload: Dictionary containing the request payload.

        Returns:
            Response generated by the local LLM.
        """

        logger.info("CareerAgent received action '%s'.", action)

        user_message = payload.get("message", "").strip()

        if not user_message:
            logger.warning("Empty message received in CareerAgent payload.")
            return "CareerAgent received an empty message."

        history = self.memory.get_session_messages(
            session_id=DEFAULT_SESSION_ID,
            agent_id=self.AGENT_ID,
            limit=DEFAULT_CONTEXT_LIMIT,
        )
        conversation_context = format_conversation_history(history)

        self.memory.save_message(
            DEFAULT_SESSION_ID, role="user", content=user_message, agent_id=self.AGENT_ID
        )

        full_prompt = f"""
System Instructions:
{self.system_prompt}

Tidigare konversation:
{conversation_context}

User Request:
"{user_message}"

Provide your professional response:
"""

        logger.debug("Sending prompt to Ollama via OllamaService...")

        response = self.llm.chat(full_prompt)

        if not response:
            logger.error("Failed to receive response from OllamaService.")
            return "Error: CareerAgent was unable to generate a response."

        self.memory.save_message(
            DEFAULT_SESSION_ID, role="agent", content=response, agent_id=self.AGENT_ID
        )

        logger.info("CareerAgent successfully processed the request.")

        return response


if __name__ == "__main__":

    print("=== TESTING CAREER AGENT ===")

    agent = CareerAgent()

    test_payload = {
        "message": (
            "Jag ska söka en tjänst som IT-säkerhetskonsult. "
            "Hjälp mig att förbättra mitt personliga brev."
        )
    }

    reply = agent.handle(
        action="execute",
        payload=test_payload
    )

    print("\nResponse from Agent:\n")
    print(reply)