from typing import Any, Dict

from core.logger import get_logger
from services.ollama_service import OllamaService
from services.prompt_loader import PromptLoader

logger = get_logger(__name__)


class CareerAgent:
    """
    CareerAgent handles career-related requests such as CV optimization,
    cover letters, interview preparation, LinkedIn optimization, and
    professional career development.
    """

    def __init__(self):
        self.llm = OllamaService()
        self.prompt_loader = PromptLoader()

        # Load the system prompt during initialization
        self.system_prompt = self.prompt_loader.load("career_agent.txt")

        logger.info("CareerAgent initialized successfully.")

    def handle(self, action: str, payload: Dict[str, Any]) -> str:
        """
        Executes a career-related request.

        Args:
            action: The requested action (e.g. "execute").
            payload: Dictionary containing the request payload.

        Returns:
            Response generated by the local LLM.
        """

        logger.info("CareerAgent received action '%s'.", action)

        user_message = payload.get("message", "").strip()

        if not user_message:
            logger.warning("Empty message received in CareerAgent payload.")
            return "CareerAgent received an empty message."

        full_prompt = f"""
System Instructions:
{self.system_prompt}

User Request:
"{user_message}"

Provide your professional response:
"""

        logger.debug("Sending prompt to Ollama via OllamaService...")

        response = self.llm.chat(full_prompt)

        if not response:
            logger.error("Failed to receive response from OllamaService.")
            return "Error: CareerAgent was unable to generate a response."

        logger.info("CareerAgent successfully processed the request.")

        return response


if __name__ == "__main__":

    print("=== TESTING CAREER AGENT ===")

    agent = CareerAgent()

    test_payload = {
        "message": (
            "Jag ska söka en tjänst som IT-säkerhetskonsult. "
            "Hjälp mig att förbättra mitt personliga brev."
        )
    }

    reply = agent.handle(
        action="execute",
        payload=test_payload
    )

    print("\nResponse from Agent:\n")
    print(reply)